language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly  
  - hhvm

before_script:
  - composer install --prefer-dist --dev

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'
