language: php
git:
    depth: 1

cache:
  directories:
    - $HOME/.composer/cache

env:
  - TWIG_VERSION=^1.28

matrix:
    include:
        - php: hhvm
          sudo: required
          dist: trusty
          group: edge
          env: HHVM=true TWIG_VERSION=^1.28
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge
          env: HHVM=true TWIG_VERSION=^1.28
        - php: 5.3
          dist: precise
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2

        # Twig 2
        - php: 7.0
          env: TWIG_VERSION='^2.0'
        - php: 7.1
          env: TWIG_VERSION='^2.0'
        - php: 7.2
          env: TWIG_VERSION='^2.0'

        # oldest possible deps for twig 1.x
        - php: 5.3 # for twig 1.x
          dist: precise
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' TWIG_VERSION=^1.28
        - php: 7.0 # for twig 2.x
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' TWIG_VERSION=^2.0
    fast_finish: true

before_script:
  - composer require twig/twig:${TWIG_VERSION} --no-update
  - composer update --prefer-dist ${COMPOSER_FLAGS}

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - if [ -z "$HHVM" ]; then vendor/bin/php-cs-fixer fix --dry-run --diff; fi

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ] ; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ] ; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'
