language: php
sudo: false
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0  
  - hhvm
env:
  - TWIG_VERSION=^1.10
  - TWIG_VERSION=2.0.x-dev
  
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer require twig/twig:${TWIG_VERSION} --no-update
  - composer install --prefer-dist

script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ] ; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ] ; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'
  
matrix:
  exclude:
  - env: TWIG_VERSION=2.0.x-dev
    php: 5.3
  - env: TWIG_VERSION=2.0.x-dev
    php: 5.4    
      